# ~/.config/starship.toml

add_newline = false


[os]
format = "[$symbol]($style)"
style = "bold blue"
disabled = false

[os.symbols]
Alpaquita = "ğŸ”” "
Alpine = "ïŒ€ "
Amazon = "ğŸ™‚ "
Android = "îœ "
Arch = "ó°£‡ "
Artix = "ïŒŸ "
CentOS = "ó±„š "
Debian = "ğŸŒ€ "
DragonFly = "ğŸ‰ "
Emscripten = "ğŸ”— "
EndeavourOS = "ïŒ¢ "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ğŸ¦… "
Gentoo = "ó°£¨ "
HardenedBSD = "ğŸ›¡ï¸ "
Illumos = "ïŒ¦ "
Linux = "ğŸ§ "
Mabox = "ğŸ“¦ "
Macos = "ï…¹ "
Manjaro = "ïŒ’ "
Mariner = "ğŸŒŠ "
MidnightBSD = "ğŸŒ˜ "
Mint = "ó°£­ "
NetBSD = "ğŸš© "
NixOS = "ïŒ“ "
OpenBSD = "ïŒ¨ "
OpenCloudOS = "â˜ï¸ "
openEuler = "ğŸ¦‰ "
openSUSE = "ïŒ” "
OracleLinux = "ğŸ¦´ "
Pop = "ïŒª "
Raspbian = "ğŸ“ "
Redhat = "ğŸ© "
RedHatEnterprise = "ó±„› "
Redox = "ğŸ§ª "
Solus = "ïŒ­ "
SUSE = "ğŸ¦ "
Ubuntu = "ó°•ˆ "
Unknown = "OSâ“"
Windows = "î˜ª "

[shell]
powershell_indicator = 'ó°¨Š'
bash_indicator = "î¯Š"
fish_indicator = "ó°ˆº"
zsh_indicator = "zîš‘h"
cmd_indicator = "î¯„"
unknown_indicator = ""
style = 'blue'
disabled = false

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character]
success_symbol = '[âœ](bold green)'
error_symbol = '[âœ](bold green)'

# Change color of Git Branch
[git_branch]
format = '\([ï˜ $branch]($style)\)'
style = "bold red"